#!/usr/bin/env perl

use strict;
use warnings;

use DateTimeX::Easy qw/datetime/;

my $category;
while (<STDIN>) {

    next if m/^\s*$/;
    next if m/^\s*#/;
    
    if (m/^\s*category:\s*(.*)/) {
        $category = $1;
    }
    else {

    }
}
