#!/usr/bin/env perl

use strict;
use warnings;

use DateTimeX::Easy qw/datetime/;
use YAML::Tiny;
use Spilack;

my $category;
my $input = join '', <STDIN>;

my $unroll = Spilack->_unroll( $input );

#print YAML::Tiny->new( $unroll )->write_string, "\n";

my $tally = Spilack->tally( $input );

my $total = 0;
for my $entry (values %$tally) {
    my ( $description, $amount ) = @$entry{ qw/ description amount / };
    print "$description: \$", (sprintf "%.2f", $amount / 100), "\n";
    $total += $amount;
}
print "Total: \$", (sprintf "%.2f", $total / 100), "\n";
